apiVersion: v2
appVersion: v0.8.0
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 15.5.38
  - name: mongodb
    version: 16.3.0
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: ollama
    version: 1.26.0
    repository: file://./ollama
    condition: ollama.enabled
  - name: meilisearch
    version: 0.7.0
    repository: file://./meilisearch
    condition: meilisearch.enabled
  - name: librechat-rag-api
    version: 0.5.1
    repository: file://./librechat-rag-api
    condition: librechat-rag-api.enabled
description: A Helm chart for deploying LibreChat, an open-source, AI-powered chat application.
home: https://www.librechat.ai
icon: https://www.librechat.ai/librechat_alt.svg
name: librechat
type: application
version: 1.8.10
keywords:
  - librechat
  - chat
  - ai
  - llm
  - chatbot
  - open-source
maintainers:
  - name: Carlos Estay
    email: cestay@redhat.com
  - name: Maximiliano Pizarro
    email: mapizarr@redhat.com
sources:
  - https://github.com/maximilianoPizarro/librechat