site_name: LibreChat Helm Chart
site_url: https://maximilianopizarro.github.io/librechat/
site_author: Maximiliano Pizarro
site_description: "Deploy LibreChat on Kubernetes & OpenShift with AI model integration"
repo_url: "https://github.com/maximilianoPizarro/librechat"

nav:
  - Home: index.md
theme: readthedocs
