{{- if not (index .Values "sccRoleDisabled" | default false) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "rag.fullname" . }}-anyuid-scc
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["security.openshift.io"]
  resourceNames: ["anyuid"]
  resources: ["securitycontextconstraints"]
  verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rag.fullname" . }}-anyuid-scc-binding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name | default "default" }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "rag.fullname" . }}-anyuid-scc
  apiGroup: rbac.authorization.k8s.io
{{- end }}
